# -*- coding: utf-8 -*-
map_to_beautifull_names = {
    'temp_aussen': 'Temp-Aussen',
    'temp_Vl': 'Temp-Vorlauf',
    'temp_RlSoll': 'Temp-Ruecklauf-Soll',
    'temp_Rl': 'Temp-Ruecklauf',
    'temp_WQaus': 'Temp-WQ-Aus',
    'temp_WQein': 'Temp-WQ-Ein',
    'temp_WW': 'Temp-WW',
    'temp_einsatz': 'Hzg:TempEinsatz',
    'temp_Kondensator': 'Temp-Kondensator',
    'temp_BasisSoll': 'Hzg:TempBasisSoll',
    'temp_Verdampfer': 'Temp-Verdampfer',
    'hzg_KlSteilheit': 'Hzg:KlSteilheit',
    'hzg_Hysterese': 'Hzg:Hysterese',
    'hzg_PumpenNachl': 'Hzg:PumpenNachl',
    'ww_Abschaltung': 'Ww:Abschaltung',
    'ww_TempSoll': 'Ww:TempSoll',
    'ww_Hysterese': 'Ww:Hysterese',
    'uhrzeit': 'Uhrzeit',
    'datum': 'Datum',
    'handabschaltung': 'Handabschaltung',
    'deltaVlRl': 'Delta-Vorlauf-Ruecklauf',
    'deltaWQea': 'Delta-WQ-Ein-WQ-Aus',
    'deltaWQaVerdamp': 'Delta-WQ-Aus-Verdampfer',
    'deltaKondensVl': 'Delta-Temp-Kondensator-Vorlauf',
    }

plotable_fields = [ 'temp_aussen',
                    'temp_Vl',
                    'temp_RlSoll',
                    'temp_Rl',
                    'temp_WQaus',
                    'temp_WQein',
                    'temp_WW',
                    'temp_einsatz',
                    'temp_Kondensator',
                    'temp_BasisSoll',
                    'temp_Verdampfer',
                    'hzg_KlSteilheit',
                    'hzg_Hysterese',
                    'hzg_PumpenNachl',
                    'ww_Abschaltung',
                    'ww_TempSoll',
                    'ww_Hysterese',
                    'deltaVlRl',
                    'deltaWQea',
                    'deltaWQaVerdamp',
                    'deltaKondensVl', ]
